spring:
  application:
    name: notification-service
  datasource:
    url: ${NOTIFICATION_DB_URL:jdbc:postgresql://localhost:5433/NOTIFICATION_DB}
    username: ${NOTIFICATION_DB_USERNAME:postgres}
    password: ${NOTIFICATION_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:none}
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: ${JPA_FORMAT_SQL:true}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${KAFKA_NOTIFICATION_GROUP_ID:notification-service-group}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  mail:
    host: ${MAIL_HOST:smtp.mailersend.com}
    port: ${MAIL_PORT:587}
    username: ${MAILERSEND_USERNAME:}
    password: ${MAILERSEND_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:false}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS:true}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8090}/realms/${KEYCLOAK_REALM:growpath}
          jwk-set-uri: ${KEYCLOAK_URL:http://localhost:8090}/realms/${KEYCLOAK_REALM:growpath}/protocol/openid-connect/certs

server:
  port: ${NOTIFICATION_SERVICE_PORT:8082}

management:
  health:
    mail:
      enabled: ${MAIL_HEALTH_ENABLED:false}
    db:
      enabled: ${DB_HEALTH_ENABLED:false}
  endpoints:
    web:
      exposure:
        include: health,info

mailersend:
  api-key: ${MAILERSEND_API_KEY:}
  from-email: ${MAILERSEND_FROM_EMAIL:noreply@growpath.local}

logging:
  level:
    org.springframework.kafka: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
